-- complete data import script for montgomery county voter access analysis
-- populates all tables from csv files generated by python processing

-- population centers table import
-- stores population-weighted centroids for each block group
truncate population_centers cascade;

create temp table temp_pop_centers (
    statefp text,
    countyfp text,
    tractce text,
    blkgrpce text,
    population text,
    latitude text,
    longitude text,
    geoid text,
    geometry text
);

copy temp_pop_centers from '/tmp/accessibility_scores_enhanced_complete.csv'
delimiter ','
csv header;

insert into population_centers (geoid, population, latitude, longitude)
select distinct 
    geoid,
    nullif(population, 'NA')::integer,
    nullif(latitude, 'NA')::double precision,
    nullif(longitude, 'NA')::double precision
from temp_pop_centers
where geoid is not null 
  and geoid like '1101%';

update population_centers 
set geom = st_setsrid(st_makepoint(longitude, latitude), 4326)
where latitude is not null and longitude is not null;

drop table temp_pop_centers;

select count(*) as population_centers_count from population_centers;

-- accessibility scores table import
-- comprehensive distance and walkability metrics for each population center
truncate accessibility_scores cascade;

create temp table temp_accessibility (
    statefp text,
    countyfp text,
    tractce text,
    blkgrpce text,
    population text,
    latitude text,
    longitude text,
    geoid text,
    geometry text,
    min_dist_to_poll_miles text,
    nearest_polling_idx text,
    min_manhattan_dist_miles text,
    min_dist_to_civic_center_miles text,
    dist_to_city_hall_miles text,
    min_dist_to_poll_miles_norm text,
    min_manhattan_dist_miles_norm text,
    min_dist_to_civic_center_miles_norm text,
    accessibility_score text,
    accessibility_category text,
    min_network_dist_miles text,
    nearest_poll_network_idx text,
    driving_to_euclidean_ratio text,
    driving_euclidean_diff_miles text,
    min_walking_dist_miles text,
    nearest_poll_walking_idx text,
    osrm_walking_to_euclidean_ratio text,
    min_google_walking_dist_miles text,
    nearest_poll_google_walking_idx text,
    google_walking_to_euclidean_ratio text,
    osrm_walking_to_driving_ratio text,
    google_to_osrm_walking_ratio text,
    google_walking_to_driving_ratio text,
    osm_has_sidewalk text,
    osm_sidewalk_count text,
    osm_total_segments text,
    osm_sidewalk_pct text,
    walkability_score text,
    walkability_category text
);

copy temp_accessibility from '/tmp/accessibility_scores_enhanced_complete.csv'
delimiter ','
csv header;

insert into accessibility_scores (
    geoid,
    euclidean_dist_miles,
    nearest_poll_id,
    manhattan_dist_miles,
    dist_to_civic_center_miles,
    dist_to_city_hall_miles,
    osrm_driving_miles,
    nearest_poll_osrm_driving_idx,
    driving_to_euclidean_ratio,
    driving_euclidean_diff_miles,
    osrm_walking_miles,
    nearest_poll_osrm_walking_idx,
    osrm_walking_to_euclidean_ratio,
    google_walking_miles,
    nearest_poll_google_walking_idx,
    google_walking_to_euclidean_ratio,
    osrm_walking_to_driving_ratio,
    google_to_osrm_walking_ratio,
    google_walking_to_driving_ratio,
    osm_has_sidewalk,
    osm_sidewalk_count,
    osm_total_segments,
    osm_sidewalk_pct,
    walkability_score,
    walkability_category
)
select 
    geoid,
    nullif(min_dist_to_poll_miles, 'NA')::double precision,
    nullif(nearest_polling_idx, 'NA')::integer,
    nullif(min_manhattan_dist_miles, 'NA')::double precision,
    nullif(min_dist_to_civic_center_miles, 'NA')::double precision,
    nullif(dist_to_city_hall_miles, 'NA')::double precision,
    nullif(min_network_dist_miles, 'NA')::double precision,
    nullif(nearest_poll_network_idx, 'NA')::integer,
    nullif(driving_to_euclidean_ratio, 'NA')::double precision,
    nullif(driving_euclidean_diff_miles, 'NA')::double precision,
    nullif(min_walking_dist_miles, 'NA')::double precision,
    nullif(nearest_poll_walking_idx, 'NA')::integer,
    nullif(osrm_walking_to_euclidean_ratio, 'NA')::double precision,
    nullif(min_google_walking_dist_miles, 'NA')::double precision,
    nullif(nearest_poll_google_walking_idx, 'NA')::integer,
    nullif(google_walking_to_euclidean_ratio, 'NA')::double precision,
    nullif(osrm_walking_to_driving_ratio, 'NA')::double precision,
    nullif(google_to_osrm_walking_ratio, 'NA')::double precision,
    nullif(google_walking_to_driving_ratio, 'NA')::double precision,
    nullif(osm_has_sidewalk, 'NA')::boolean,
    nullif(osm_sidewalk_count, 'NA')::integer,
    nullif(osm_total_segments, 'NA')::integer,
    nullif(osm_sidewalk_pct, 'NA')::double precision,
    nullif(walkability_score, 'NA')::double precision,
    walkability_category
from temp_accessibility
where geoid is not null
  and geoid like '1101%';

drop table temp_accessibility;

select count(*) as accessibility_count from accessibility_scores;

-- isochrone summary table import
-- aggregated metrics for walkable areas around each polling place
truncate isochrone_summary;

create temp table temp_isochrone (
    polling_place text,
    time_minutes text,
    area_sq_miles text,
    population_served text
);

copy temp_isochrone from '/tmp/polling_isochrone_summary.csv'
delimiter ','
csv header;

insert into isochrone_summary (polling_place_name, time_minutes, area_sq_miles, population_served)
select 
    polling_place,
    nullif(time_minutes, 'NA')::integer,
    nullif(area_sq_miles, 'NA')::double precision,
    nullif(population_served, 'NA')::integer
from temp_isochrone;

drop table temp_isochrone;

select count(*) as isochrone_count from isochrone_summary;

-- county turnout data insertion
-- registration and participation statistics for montgomery county
truncate county_turnout;

insert into county_turnout (county_name, election_year, registered_voters, total_ballots)
values 
    ('Montgomery', 2020, 165228, 99286);

select * from county_turnout;

-- precinct boundaries for 2020 election
-- spatial boundaries of voting precincts as they existed in 2020
truncate precincts_2020 cascade;

create temp table temp_precincts_2020 (
    statefp20 text,
    countyfp text,
    vtdst20 text,
    geoid20 text,
    precinct text,
    g20prertru text,
    g20predbid text,
    g20preljor text,
    g20preowri text,
    g20ussrtub text,
    g20ussdjon text,
    g20ussowri text,
    g20sscrsha text,
    g20sscowri text,
    g20sscrmen text,
    g20sscowr2 text,
    g20sacrtho text,
    g20sacowri text,
    g20sacrfri text,
    g20sacowr2 text,
    g20sccrwin text,
    g20sccowri text,
    g20sccrkel text,
    g20sccowr2 text,
    g20pscrcav text,
    g20pscdcas text,
    g20pscowri text,
    dem_pres text,
    rep_pres text,
    lib_pres text,
    writein_pres text,
    total_pres_votes_2020 text,
    dem_share_2020 text
);

copy temp_precincts_2020 from '/tmp/montgomery_precinct_results_2020.csv'
delimiter ','
csv header;

insert into precincts_2020 (geoid, county_fips, vtdst, geoid20, name, state_fips)
select 
    geoid20,
    countyfp,
    vtdst20,
    geoid20,
    precinct,
    '01'
from temp_precincts_2020
where geoid20 is not null;

drop table temp_precincts_2020;

select count(*) as precincts_2020_count from precincts_2020;

-- precinct boundaries for 2024 election
-- spatial boundaries of voting precincts after redistricting
truncate precincts_2024 cascade;

create temp table temp_precincts_2024 (like precincts_2024);
alter table temp_precincts_2024 add column unique_id text;
alter table temp_precincts_2024 add column county text;
alter table temp_precincts_2024 add column precinct text;

copy temp_precincts_2024 from '/tmp/montgomery_precinct_results_2024.csv'
delimiter ','
csv header;

insert into precincts_2024 (geoid, county_fips, county, name, state_fips)
select 
    unique_id,
    '101',
    county,
    precinct,
    '01'
from temp_precincts_2024
where unique_id is not null;

drop table temp_precincts_2024;

select count(*) as precincts_2024_count from precincts_2024;

-- election results for 2020 general election
-- vote counts aggregated by precinct
truncate election_results_2020;

create temp table temp_election_2020 as select * from precincts_2020 limit 0;
alter table temp_election_2020 add column dem_pres text;
alter table temp_election_2020 add column rep_pres text;
alter table temp_election_2020 add column lib_pres text;
alter table temp_election_2020 add column writein_pres text;
alter table temp_election_2020 add column g20ussrtub text;
alter table temp_election_2020 add column g20ussdjon text;

copy temp_election_2020 from '/tmp/montgomery_precinct_results_2020.csv'
delimiter ','
csv header;

insert into election_results_2020 (precinct_geoid, rep_pres_votes, dem_pres_votes, lib_pres_votes, writein_pres_votes, rep_senate_votes, dem_senate_votes)
select 
    geoid20,
    nullif(rep_pres, 'NA')::integer,
    nullif(dem_pres, 'NA')::integer,
    nullif(lib_pres, 'NA')::integer,
    nullif(writein_pres, 'NA')::integer,
    nullif(g20ussrtub, 'NA')::integer,
    nullif(g20ussdjon, 'NA')::integer
from temp_election_2020
where geoid20 is not null;

drop table temp_election_2020;

select count(*) as election_2020_count from election_results_2020;

-- election results for 2024 general election
-- vote counts aggregated by precinct
truncate election_results_2024;

create temp table temp_election_2024_raw (
    unique_id text,
    countyfp text,
    county text,
    precinct text,
    g24a01no text,
    g24a01yes text,
    g24aj1owri text,
    g24aj1rmcc text,
    g24aj2owri text,
    g24aj2rbry text,
    g24aj3owri text,
    g24aj3rsel text,
    g24aj4owri text,
    g24aj4rmit text,
    g24cfjdgri text,
    g24cfjowri text,
    g24cfjrste text,
    g24cr1owri text,
    g24cr1rmin text,
    g24cr2owri text,
    g24cr2rand text,
    g24cr3owri text,
    g24cr3rcol text,
    g24cv1owri text,
    g24cv1redw text,
    g24cv2owri text,
    g24cv2rhan text,
    g24cv3owri text,
    g24cv3rmoo text,
    g24predhar text,
    g24preiken text,
    g24preioli text,
    g24preiste text,
    g24preowri text,
    g24prertru text,
    g24pscowri text,
    g24pscrcav text,
    gcon01dhol text,
    gcon01owri text,
    gcon01rmoo text,
    gcon02dfig text,
    gcon02owri text,
    gcon02rdob text,
    gcon03owri text,
    gcon03rrog text,
    gcon04owri text,
    gcon04rade text,
    gcon05owri text,
    gcon05rstr text,
    gcon06dand text,
    gcon06owri text,
    gcon06rpal text,
    gcon07dsew text,
    gcon07owri text,
    gcon07rlit text,
    dem_pres text,
    rep_pres text,
    ind_pres_kennedy text,
    ind_pres_oliver text,
    ind_pres_stein text,
    writein_pres text,
    total_pres_votes_2024 text,
    dem_share_2024 text
);

copy temp_election_2024_raw from '/tmp/montgomery_precinct_results_2024.csv'
delimiter ','
csv header;

insert into election_results_2024 (precinct_geoid, dem_pres_votes, rep_pres_votes, ind_pres_kennedy_votes, ind_pres_oliver_votes, ind_pres_stein_votes, writein_pres_votes)
select 
    unique_id,
    nullif(dem_pres, 'NA')::integer,
    nullif(rep_pres, 'NA')::integer,
    nullif(ind_pres_kennedy, 'NA')::integer,
    nullif(ind_pres_oliver, 'NA')::integer,
    nullif(ind_pres_stein, 'NA')::integer,
    nullif(writein_pres, 'NA')::integer
from temp_election_2024_raw
where unique_id is not null;

drop table temp_election_2024_raw;

select count(*) as election_2024_count from election_results_2024;

-- vulnerability index calculation at block group level
-- composite score identifying communities with multiple accessibility barriers
truncate vulnerability_index;

insert into vulnerability_index (geoid, z_pct_black, z_pct_poverty, z_pct_no_vehicle, vulnerability_score, vulnerability_category)
select 
    geoid,
    (pct_black - avg(pct_black) over()) / nullif(stddev(pct_black) over(), 0) as z_pct_black,
    (pct_poverty - avg(pct_poverty) over()) / nullif(stddev(pct_poverty) over(), 0) as z_pct_poverty,
    (pct_no_vehicle - avg(pct_no_vehicle) over()) / nullif(stddev(pct_no_vehicle) over(), 0) as z_pct_no_vehicle,
    (coalesce((pct_black - avg(pct_black) over()) / nullif(stddev(pct_black) over(), 0), 0) + 
     coalesce((pct_poverty - avg(pct_poverty) over()) / nullif(stddev(pct_poverty) over(), 0), 0) + 
     coalesce((pct_no_vehicle - avg(pct_no_vehicle) over()) / nullif(stddev(pct_no_vehicle) over(), 0), 0)) / 3.0 as vulnerability_score,
    case 
        when (coalesce((pct_black - avg(pct_black) over()) / nullif(stddev(pct_black) over(), 0), 0) + 
              coalesce((pct_poverty - avg(pct_poverty) over()) / nullif(stddev(pct_poverty) over(), 0), 0) + 
              coalesce((pct_no_vehicle - avg(pct_no_vehicle) over()) / nullif(stddev(pct_no_vehicle) over(), 0), 0)) / 3.0 > 1.0 then 'High'
        when (coalesce((pct_black - avg(pct_black) over()) / nullif(stddev(pct_black) over(), 0), 0) + 
              coalesce((pct_poverty - avg(pct_poverty) over()) / nullif(stddev(pct_poverty) over(), 0), 0) + 
              coalesce((pct_no_vehicle - avg(pct_no_vehicle) over()) / nullif(stddev(pct_no_vehicle) over(), 0), 0)) / 3.0 > 0.0 then 'Moderate'
        when (coalesce((pct_black - avg(pct_black) over()) / nullif(stddev(pct_black) over(), 0), 0) + 
              coalesce((pct_poverty - avg(pct_poverty) over()) / nullif(stddev(pct_poverty) over(), 0), 0) + 
              coalesce((pct_no_vehicle - avg(pct_no_vehicle) over()) / nullif(stddev(pct_no_vehicle) over(), 0), 0)) / 3.0 > -1.0 then 'Low'
        else 'Very Low'
    end as vulnerability_category
from demographics_bg
where pct_black is not null;

select count(*) as vulnerability_count from vulnerability_index;

-- verification query to confirm all tables populated correctly
select 'demographics_bg' as table_name, count(*) as row_count from demographics_bg
union all
select 'population_centers', count(*) from population_centers
union all
select 'accessibility_scores', count(*) from accessibility_scores
union all
select 'isochrone_summary', count(*) from isochrone_summary
union all
select 'county_turnout', count(*) from county_turnout
union all
select 'precincts_2020', count(*) from precincts_2020
union all
select 'precincts_2024', count(*) from precincts_2024
union all
select 'election_results_2020', count(*) from election_results_2020
union all
select 'election_results_2024', count(*) from election_results_2024
union all
select 'vulnerability_index', count(*) from vulnerability_index;